spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexbuy_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: kevin
    password: kevin12345.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations:
        - classpath:users.sql
        - classpath:category.sql
        - classpath:sub_category.sql
      continue-on-error: true
      platform: mysql

  mail:
    host: smtp.gmail.com
    port: 587
    username: kscozzari03@gmail.com
    password: hrnp gfah bxts hzly
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true # Opzionale per sviluppo

  freemarker:
    template-loader-path: classpath:/templates